"""Add difficulty to quests

Revision ID: e133cfb79e06
Revises: 
Create Date: 2025-03-24 22:42:05.778655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e133cfb79e06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='leveldifficulty'), server_default='EASY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'difficulty')
    # ### end Alembic commands ###
