"""Add unique constraint to user_profiles.user_id

Revision ID: fee39d3908ae
Revises: e133cfb79e06
Create Date: 2025-03-24 23:20:09.616438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee39d3908ae'
down_revision: Union[str, None] = 'e133cfb79e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_profile', 'user_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_profile', 'user_profiles', type_='unique')
    # ### end Alembic commands ###
